# Generated by Django 5.0.6 on 2025-01-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_class_instructor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='instructor_name',
            field=models.CharField(max_length=20),
        ),
    ]
