# Generated by Django 5.0.6 on 2025-01-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_class_instructor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='instructor_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
