# Generated by Django 5.0.6 on 2025-01-12 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_user_instructor_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='instructor_name',
        ),
    ]
